### ISSUE TITLE
Update userguide

### ISSUE THREAD

**Issue by chlab** [sephii/taxi#100]
The [user guide](https://taxi-timesheets.readthedocs.org/en/master/userguide.html) says "You’ll probably want to install a backend as well" and refers you to the [zebra backend](https://github.com/sephii/taxi-zebra).

There it says to update your .taxirc file, which at that point does not yet exist. So I created it. 
Running taxi update with a partial .taxirc file will cause an error (attached).

You can just update the doc to say to run `taxi update` first.

<img width="716" alt="screen shot 2016-04-06 at 11 51 19" src="https://cloud.githubusercontent.com/assets/1931446/14314123/c848d874-fbf5-11e5-8a36-029c19074340.png">

**Comment by sephii** [comment]
Things should be better with 4.2 user docs. Let me know if it's still not clear.
