### ISSUE TITLE
Alias case sensitivity

### ISSUE THREAD

**Issue by schtibe** [sephii/taxi#107]
Sometimes aliases are added in upper (or mixed case), for example: OKA_dev.
It is not possible to use OKA_dev in taxi then, since apparently all aliases are handled in lower case in taxi. This might be very confusing for someone who looks up the alias in Zebra.

**Comment by sephii** [comment]
I could reproduce it. That's caused by Python's `ConfigParser` module that automatically lowercases options keys. We could either make aliases case insensitive, or preserve the case when saving them. I'm not sure which option is better.

**Comment by jeanmonod** [comment]
Why not resolve that upfront and lover all aliases in Zebra already? I don't see an added value to allow uppercase in aliases

**Comment by jeanmonod** [comment]
Task ticket Zebra side: https://jira.liip.ch/browse/ZBR-1785

**Comment by sephii** [comment]
Thanks, closing it on this side then.
