### ISSUE TITLE
`taxi stop` does not work

### ISSUE THREAD

**Issue by sosterwalder** [sephii/taxi#115]
When using `taxi stop`, it throws an error: `AttributeError: 'Timesheet' object has no attribute 'round_to_quarter'`

I see two solutions here:
* Move method `round_to_quarter` from module to class (if it has no dependencies)
* Create wrapper `round_to_quarter` within `Timesheet` class, which calls the method class (in case there are dependencies)

**Comment by sephii** [comment]
Fixed in Taxi 4.4.2, thanks for reporting.
