### ISSUE TITLE
`taxi stop` gets rid of the description

### ISSUE THREAD

**Issue by sosterwalder** [sephii/taxi#116]
When using the `taxi stop` command, it enters the time correctly, but cuts the before given description, leaving an empty description what results in an error:

```bash
Error: Parse error in /path/to/foo.tks at line N: Line must have an
alias, a duration and a description. The line causing the error was:```

**Comment by sephii** [comment]
Can you paste the exact command you ran that resulted in this error? According to the code (https://github.com/sephii/taxi/blob/master/taxi/timesheet/timesheet.py#L127), the description should not be changed if the provided description is `None`, but maybe click passes an empty string instead.

**Comment by sephii** [comment]
I think this was related to https://github.com/sephii/taxi/pull/111. I'll close this for now, feel free to reopen it if the issue persists.
