### ISSUE TITLE
Better separate commits with role assignation to avoid mistakes

### ISSUE THREAD

**Issue by LeBenLeBen** [sephii/taxi#119]
```
➜ taxi ci
Pushing entries...

_ls_telecom 0.75  description (as Telecommunication ❮ Office care ❮ Liip Lausanne ❮ GCC)

You're trying to push "Setup massages" on the _ls_health alias, which doesn't have any role set.

In which role do you want to push this entry?

[0] Telecommunication ❮ Office care ❮ Liip Lausanne ❮ GCC
...
[16] Health coordinator ❮ Office care ❮ Liip Lausanne ❮ GCC
-----
[i] Individual action ❮ YOLO
[c] Cancel, skip this entry for now

Select a role: 0
You have selected the role Telecommunication ❮ Office care ❮ Liip Lausanne ❮ GCC
```

It's not the first time I make the mistake so I think this is something that could be improved. In the example above I thought the first commit was the one about _ls_telecom but it was actually about _ls_healt. A separation line at the beginning of the "pick a role" thing would helps a lot I think.

**Comment by sephii** [comment]
Thanks for the report. You're not the first one to make this mistake and I agree with you the current process is confusing.

I'm closing this report in favour of https://github.com/sephii/taxi-zebra/issues/13 though, since I prefer the other proposal. Feel free to comment there if you want!
