### ISSUE TITLE
Replace taxi start/stop by only taxi stop

### ISSUE THREAD

**Issue by OdyX** [sephii/taxi#37]
As discussed, I have the feeling that a single "taxi stop" command (without requiring the use of an earlier taxi start), could be useful:
- When you arrive in the morning:

```
taxi enginestart (adds a time for the arrival)
```
- After each completed task:

```
taxi pitstop activity_code "activity description"
```

What do you think?

**Comment by sephii** [comment]
@jeanmonod we could just support a second argument to `taxi start` to be able to directly set the description of the new entry, and make the description in `taxi stop` optional. What do you think?

**Comment by jeanmonod** [comment]
This was in 2014 ;) For me it's no more a priority. Right know I keep my taxi file open all day long and constantly refactor the entries. So I wont be a user of those features...

**Comment by sephii** [comment]
Ok let's drop this for now then.
