### ISSUE TITLE
Separate taxi from Zebra and allow to have multiple backends

### ISSUE THREAD

**Issue by jeanmonod** [sephii/taxi#40]
If we completely separate taxi from the zebra backend, this will have major benefits:

* It will make taxi a real opensource project, useful outside Liip
* Taxi will be able to push entries to public backend such as Harvest, 10000ft or even a basic spreadsheet. This should boost the community support
* Personably I will be able to timesheet my personal project with my favorite timesheet tool... ;)

So in my idea, each aliases could be bound to a specific backend, and then when I do a taxi ci, the entries will be pushed to appropriate location.

What do you think about that? This goes in the same spirit as #24, #29 but one step ahead...

**Comment by sephii** [comment]
The feature is done and has been merged in dev. The zebra backend has been put here: https://github.com/sephii/taxi-zebra.

**Comment by jeanmonod** [comment]
I would suggest to move the taxi-zebra under liip (private repo), or even
under gitlab/liip. What do you think?

On Mon, Feb 16, 2015 at 9:32 AM, Sylvain Fankhauser <
notifications@github.com> wrote:

> The feature is done and has been merged in dev. The zebra backend has been
> put here: https://github.com/sephii/taxi-zebra.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sephii/taxi/issues/40#issuecomment-74474128>.
>



-- 
David Jeanmonod
david.jeanmonod@gmail.com
077 437 51 12

**Comment by sephii** [comment]
Zebra being open source I'm not sure it would make sense to have this in a private repo. Also, not releasing taxi-zebra publicly would mean not being able to simply install it with `pip install taxi-zebra`.

**Comment by jeanmonod** [comment]
Zebra open source??

On Mon, Feb 16, 2015 at 11:27 AM, Sylvain Fankhauser <
notifications@github.com> wrote:

> Zebra being open source I'm not sure it would make sense to have this in a
> private repo. Also, not releasing taxi-zebra publicly would mean not being
> able to simply install it with pip install taxi-zebra.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sephii/taxi/issues/40#issuecomment-74487447>.
>



-- 
David Jeanmonod
david.jeanmonod@gmail.com
077 437 51 12

**Comment by sephii** [comment]
Let's put taxi-zebra on Pypi, so that users can easily install it with pip, and host it on github as a read-only mirror of an internal repository that will be used for bug reporting.

Anyway, this feature has been implemented in a6fc5a7181bb51beac5071e623884f7ef3f20539 and has been merged in dev.
