### ISSUE TITLE
Don't comment pushed entries

### ISSUE THREAD

**Issue by sephii** [sephii/taxi#72]
Instead of commenting pushed entries, it would make more sense to mark them as pushed. This would avoid annoying operations like fixing start time, and would allow running operations on pushed entries (eg. show a summary of last week entries). This would also pave the way for 2-way sync, although I'm not sure this is an important feature.

I guess adding a character at the start of the line would be the way to go, as it would also allow to use other markers, for example to ignore an entry. A pushed entry could look like that:

`= taxi 0800-0845 Work on taxi`

Here the `=` sign denotes a pushed entry. We could use the `?` sign for ignored entries, thus removing the current hack involving the question mark at the end of the alias:

`? taxi 0800-0845 Work on taxi`

**Comment by jeanmonod** [comment]
+10000 on this one!
What you could do too, is to keep as it is and still parse the commented lines. I know you don't like the idea, but it's almost the same.
Thanks for going that way

**Comment by sephii** [comment]
Following discussion from #60:

Currently flags are in the following places:

* Start of a line/alias (ignored flag, pushed flag)
* End of an alias (ignored flag)

I think regrouping them to only 1 place (start of a line) would be cleaner.

**Comment by colinfrei** [comment]
As mentioned in #60, please make the characters configurable.

**Comment by sephii** [comment]
Fixed in https://github.com/sephii/taxi/commit/dc1c27af33ac6c1b3ec714479ed11e2c917758dc.
