### ISSUE TITLE
Create a Zebra compare command

### ISSUE THREAD

**Issue by sitron** [sephii/taxi#73]
It would be fantastic to have a "zebra-compare --date=xxx" (or --date-range xxx)
Especially today...

**Comment by sephii** [comment]
+1, that would be nice. Unfortunately this is not possible with the current entries file syntax, as pushed entries are commented and thus ignored when parsing timesheets.

However once https://github.com/sephii/taxi/issues/72 is done, it will be possible to implement.

**Comment by gnutix** [comment]
Shouldn't this issue be moved to the https://github.com/sephii/taxi-zebra repository ?

**Comment by sephii** [comment]
Indeed. Closing it here. @sitron if you’re still interested in this, please reopen the issue on the taxi-zebra tracker (and feel free to submit a PR ;)).
