### ISSUE TITLE
Bug in line commenting when there is a grouped entry

### ISSUE THREAD

**Issue by jeanmonod** [sephii/taxi#76]
````
taxi ci
Pushing entries...
_zebra (2184/88)               1.75  Setup a new backlog, cleanup
_crm (2008/88)                 2.00  Jira cleanup - Failed, reason: ProjectClosedEnd
pia_pos (2206/1304)            0.25  Emails followup
Total pushed                   2.00
Failed entries
<taxi.timesheet.entry.AggregatedTimesheetEntry object at 0x10a073e10> - ProjectClosedEnd
Total failed                   2.00

taxi edit
353 # _zebra          -1500         Setup a new backlog, cleanup
354 _crm            1500-1630     Jira cleanup
355 # pia_pos         2215-2230     Emails followup
356 _crm            -2300         Jira cleanup
Staging changes :
# Monday 02 march #
_crm (2008/88)                 8.00  Jira cleanup
Total                          8.00
````

Personally, I would suggest you to remove the concept of aggregated entries. It add a lot of complexity to the project and doesn't bring any added value...

**Comment by sephii** [comment]
Already fixed : https://github.com/sephii/taxi/issues/66. Should have been part of 3.2.2 but this version will probably get dropped in favor of 4.0.

IMO grouping entries allows you to get a better overview of what you've worked on.

**Comment by jeanmonod** [comment]
What I don't like with grouping is that your taxi file is no more in sync with zebra. So it's hard to compare sometime... Is there an option to deactivate that feature?

**Comment by sephii** [comment]
Not yet but it would be easy to do. Can you create a new issue for that please?
