### ISSUE TITLE
Pushed line should be commented directly after the push (one by one)

### ISSUE THREAD

**Issue by jeanmonod** [sephii/taxi#82]
Currently, if the ci action fail, or if you ctrl+c a commit, the status of the file is not good. You can have pushed 9 entries without any one of them commented in the source file. This is very dangerous...

**Comment by sephii** [comment]
Any exception raised during the committing phase are already catched, except for the Ctrl-C one you mentioned. It's now fixed.

**Comment by jeanmonod** [comment]
Perfect thanks!
