### ISSUE TITLE
Allow to explore an alias with taxi show

### ISSUE THREAD

**Issue by jeanmonod** [sephii/taxi#87]
When I want to know what is doing an alias, I always do a `taxi show xxx` and got the error:

    [dj]/Users/dj/Projects/zebra|zbr-845>taxi show _trainee_coaching
    Usage: taxi show [OPTIONS] PROJECT_ID [BACKEND]
    Error: Invalid value for "project_id": _trainee_coaching is not a valid integer

Can we make `taxi show` working for aliases too? (I know that there is `taxi alias`, but `show` seems to be more intuitive...)

**Comment by sephii** [comment]
I agree with you, and I think the whole show/search/alias/add is a bit too complicated now. I need to think about a better way to deal with this.

**Comment by sephii** [comment]
Will be fixed in #90.
