### ISSUE TITLE
Regression, description with ? are valid again

### ISSUE THREAD

**Issue by jeanmonod** [sephii/taxi#88]
Since https://github.com/sephii/taxi/pull/52 it was possible to have pending description. But today I just accidentally pushed a series of line with `?` as description...

**Comment by sephii** [comment]
I couldn't find any trace of a possible #52 implementation in the code, so I don't think it was ever done. I'm not sure why the issue was closed though. Anyway I would prefer using the ignore flag discussed in #72 instead.
