### ISSUE TITLE
Merge commands "show", "alias", "add", "search"

### ISSUE THREAD

**Issue by sephii** [sephii/taxi#90]
These 4 commands deal with projects and aliases. It would be better to have a single entry point instead of 4 different commands. The following need to be implemented:

* alias (lists all aliases)
* alias foo_ (lists all aliases starting with foo_)
* alias foo_bar 123/456 (adds alias foo_bar, mapping it to 123/456)
* alias 123 (lists all aliases defined for the given project)
* alias 123/456 (shows the alias defined for the given project/activity tuple)
* add foo_bar (searches for projects named foo_bar and interactively add an alias for one of its activities)
* search foo_bar (lists projects named foo_bar)
* show 123 (shows details of project 123)

We could use a notation similar to `git remote`:

* alias (alias for "alias list", displays all aliases)
* alias [list] foo_
* alias [list] 123
* alias [list] 123/456
* alias add foo_bar 123/456
* alias add foo_bar (equivalent to "add foo_bar")

Now the `search` and `show` commands are not directly related to aliases so maybe they should still be part of a `projects` commands or something like that...

Also this issue is a super-issue for:

* https://github.com/sephii/taxi/issues/89
* https://github.com/sephii/taxi/issues/87

**Comment by sitron** [comment]
is there anything preventing from using integer (123) as an alias? I guess not... meaning it would be hard to differentiate between alias foo_ and alias 123 above no?

**Comment by sephii** [comment]
That's a good point. Maybe we should then use a different subcommand to differentiate between alias and project searching?

**Comment by sephii** [comment]
Here's another proposal that would cover the commands `alias`, `search`, `add`, and `show`:

* `alias [list] [<search_string>]` (lists all aliases, optionally only showing the ones that match the search string)
* `alias show [--reverse] <alias/id>` (shows the mapping of a given alias or the reverse mapping by giving an id and showing the aliases that map to it)
* `alias add <alias> <mapping>` (adds the given mapping)
* `project [list] [--add] [<search_string>]` (lists all projects, optionally showing only the ones that match the search string. The `--add` option would replace `taxi add`)
* `project show <project_id>` (shows the details of the given project id)

**Comment by sephii** [comment]
Fixed by https://github.com/sephii/taxi/commit/34ad147f11a9f75e974f1a4eb37988d08d7f1133.
